version: '3'
services:

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: viernes_audios
    ports:
      - "3306:3306"
    volumes:
      - ./database/viernes_audios.sql:/docker-entrypoint-initdb.d/viernes_audios.sql

  backend:
    build: ./backend
    depends_on:
      - database
    ports:
      - "8080:8080"