name: Build and Deploy

on:
  workflow_run:
    workflows: ["Build and Testing"]
    types:
      - completed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build y push imagenes a DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          cd backend
          docker build -t $DOCKERHUB_USERNAME/ingsw3-integrador-backend:latest .
          docker push $DOCKERHUB_USERNAME/ingsw3-integrador-backend:latest
          cd ../frontend
          docker build -t $DOCKERHUB_USERNAME/ingsw3-integrador-frontend:latest .
          docker push $DOCKERHUB_USERNAME/ingsw3-integrador-frontend:latest
          cd ../database
          docker build -t $DOCKERHUB_USERNAME/mysql:latest .
          docker push $DOCKERHUB_USERNAME/mysql:latest

      - name: Configurar auth Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          service_account_key: ${{ secrets.GOOGLECLOUD_KEY }}
          project_id: viernes-2004033

      - name: Deploy Frontend
        run: |
          gcloud run deploy gc-ingsw3-integrador-frontend \
            --image=docker.io/octaviogarcia/ingsw3-integrador-frontend:latest \
            --platform=managed \
            --region=southamerica-east1 \
            --allow-unauthenticated

      - name: Deploy Backend
        run: |
          gcloud run deploy gc-ingsw3-integrador-backend \
            --image=docker.io/octaviogarcia/ingsw3-integrador-backend:latest \
            --update-env-vars INSTANCE_CONNECTION_NAME=viernes-2004033:us-central1:prueba,DB_HOST=bavblrjndfh1pissg40y-mysql.services.clever-cloud.com,DB_PORT=3306,DB_USER=uxdybzscsblyftbr,DB_PASSWORD=M56ZoQ0eXHcarlvOQ7B2,DB_DATABASE=bavblrjndfh1pissg40y \
            --platform=managed \
            --region=southamerica-east1 \
            --allow-unauthenticated