name: Build and Deploy

on:
  workflow_run:
    workflows: ["Build and Testing"]
    types:
      - completed

env:

  PROJECT_ID: ${{ secrets.GOOGLECLOUD_PROJECT }}
  REGION: us-central1
  REPO_NAME: nextjs-cloud-run

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLECLOUD_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and tag the docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |-
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          cd backend
          docker build -t $DOCKERHUB_USERNAME/craftech-test-backend:latest .
          docker push $DOCKERHUB_USERNAME/craftech-test-backend:latest
          cd ../frontend
          docker build -t $DOCKERHUB_USERNAME/craftech-test-frontend:latest .
          docker push $DOCKERHUB_USERNAME/craftech-test-frontend:latest
          cd ../database
          docker build -t $DOCKERHUB_USERNAME/mysql:latest .
          docker push $DOCKERHUB_USERNAME/mysql:latest

      - name: Push the image to the Google Container Registry (GCR)
        run: |-
          docker tag octaviogarcia/craftech-test-frontend:latest gcr.io/craftech-test/gc-ct-frontend
          docker tag octaviogarcia/craftech-test-backend:latest gcr.io/craftech-test/gc-ct-backend
          docker push gcr.io/craftech-test/gc-ct-frontend:latest
          docker push gcr.io/craftech-test/gc-ct-backend:latest

      - name: Deploy Frontend
        run: |-
          gcloud run deploy gc-ct-frontend \
          --region $REGION \
          --image gcr.io/craftech-test/gc-ct-frontend:latest \
          --platform "managed" \
          --quiet
      
      - name: Deploy Backend
        run: |-
          gcloud run deploy gc-ct-backend \
          --region $REGION \
          --image gcr.io/craftech-test/gc-ct-backend:latest \
          --platform "managed" \
          --quiet
