name: Build and Testing

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run 
        run: |
           docker compose up -d
           sleep 30

      - name: Run Tests
        run: |
          chmod +x ./node_modules/.bin/mocha
          npx mocha tests.js
        working-directory: ./backend
      
      - name: Run frontend
        run: |
          npm install --force
          nohup npm start &
        working-directory: ./frontend

      - name: Install dependencies
        run: |
          npx playwright install --force
          npm install
        working-directory: ./frontend
  
      - name: Run e2e tests
        run: xvfb-run npx codeceptjs run
        working-directory: ./frontend
  
      - name: Results
        uses: actions/upload-artifact@v2
        with:
          name: codecept-results
          path: output

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Tag and push Docker images
        run: |
          docker tag ingsw3-integrador-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/ingsw3-integrador-backend:latest
          docker tag mysql ${{ secrets.DOCKERHUB_USERNAME }}/mysql

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ingsw3-integrador-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mysql

          
