name: Tests de Integracion

on:
  workflow_run:
    workflows: ["Build and Deploy - DONT RUN"]
    types:
      - completed

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        npx playwright install --force
        npm install --force
      working-directory: ./frontend

    - name: Run test
      run: xvfb-run npx codeceptjs run
      working-directory: ./frontend

    - name: Results
      uses: actions/upload-artifact@v2
      with:
        name: codecept-results
        path: output
    